// ui/src/app/features/models/model-form/model-form.component.ts
import { Component, inject, OnInit, signal } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { MatCardModule } from '@angular/material/card';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatSelectModule } from '@angular/material/select';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { MatSnackBar, MatSnackBarModule } from '@angular/material/snack-bar';
import { ModelService } from '../../../core/services/model.service';
import { ModelStatus } from '../../../shared/models/model.interface';

@Component({
  selector: 'app-model-form',
  standalone: true,
  imports: [
    ReactiveFormsModule,
    MatCardModule,
    MatFormFieldModule,
    MatInputModule,
    MatSelectModule,
    MatButtonModule,
    MatIconModule,
    MatProgressSpinnerModule,
    MatSnackBarModule,
  ],
  templateUrl: './model-form.component.html',
  styleUrl: './model-form.component.scss',
})
export class ModelFormComponent implements OnInit {
  private readonly fb = inject(FormBuilder);
  private readonly route = inject(ActivatedRoute);
  private readonly router = inject(Router);
  private readonly modelService = inject(ModelService);
  private readonly snackBar = inject(MatSnackBar);

  readonly loading = signal(false);
  readonly saving = signal(false);
  readonly isEdit = signal(false);
  readonly modelId = signal<string | null>(null);
  readonly statusOptions: ModelStatus[] = ['Draft', 'Active', 'Archived'];

  readonly form = this.fb.group({
    name: ['', [Validators.required, Validators.maxLength(200)]],
    description: ['', [Validators.maxLength(2000)]],
    status: ['Draft' as ModelStatus],
    parameters: [''],
  });

  ngOnInit(): void {
    const id = this.route.snapshot.paramMap.get('id');
    if (id) {
      this.isEdit.set(true);
      this.modelId.set(id);
      this.loadModel(id);
    }
  }

  onSubmit(): void {
    if (this.form.invalid) return;

    this.saving.set(true);
    const { name, description, status, parameters } = this.form.value;

    let parsedParams: Record<string, unknown> | null = null;
    if (parameters?.trim()) {
      try {
        parsedParams = JSON.parse(parameters);
      } catch (e) {
        console.warn('[ModelFormComponent] Invalid JSON in Parameters field', e);
        this.snackBar.open('Invalid JSON in Parameters field', 'OK', { duration: 3000 });
        this.saving.set(false);
        return;
      }
    }

    if (this.isEdit()) {
      this.modelService.updateModel(this.modelId()!, {
        name: name!,
        description: description || null,
        status: status as ModelStatus,
        parameters: parsedParams,
      }).subscribe({
        next: model => {
          this.snackBar.open('Model updated', 'OK', { duration: 3000 });
          this.router.navigate(['/models', model.id]);
        },
        error: (err: unknown) => {
          console.error('[ModelFormComponent] Failed to update model', this.modelId(), err);
          this.snackBar.open('Failed to update model', 'OK', { duration: 3000 });
          this.saving.set(false);
        },
      });
    } else {
      this.modelService.createModel({
        name: name!,
        description: description || null,
        parameters: parsedParams,
      }).subscribe({
        next: model => {
          this.snackBar.open('Model created', 'OK', { duration: 3000 });
          this.router.navigate(['/models', model.id]);
        },
        error: (err: unknown) => {
          console.error('[ModelFormComponent] Failed to create model', err);
          this.snackBar.open('Failed to create model', 'OK', { duration: 3000 });
          this.saving.set(false);
        },
      });
    }
  }

  onCancel(): void {
    if (this.isEdit()) {
      this.router.navigate(['/models', this.modelId()]);
    } else {
      this.router.navigate(['/models']);
    }
  }

  private loadModel(id: string): void {
    this.loading.set(true);
    this.modelService.getModel(id).subscribe({
      next: model => {
        this.form.patchValue({
          name: model.name,
          description: model.description ?? '',
          status: model.status,
          parameters: model.parameters ? JSON.stringify(model.parameters, null, 2) : '',
        });
        this.loading.set(false);
      },
      error: (err: unknown) => {
        console.error('[ModelFormComponent] Failed to load model for editing', id, err);
        this.snackBar.open('Model not found', 'OK', { duration: 3000 });
        this.router.navigate(['/models']);
      },
    });
  }
}

<div class="page-container">
  <div class="page-header">
    <h1 class="page-title">{{ isEdit() ? 'Edit Model' : 'New Model' }}</h1>
  </div>

  @if (loading()) {
    <div class="loading-container">
      <mat-spinner diameter="40"></mat-spinner>
    </div>
  } @else {
    <mat-card>
      <mat-card-content>
        <form [formGroup]="form" (ngSubmit)="onSubmit()" class="model-form">
          <mat-form-field appearance="outline" class="full-width">
            <mat-label>Name</mat-label>
            <input matInput formControlName="name" placeholder="Enter model name" maxlength="200">
            @if (form.controls.name.hasError('required')) {
              <mat-error>Name is required</mat-error>
            }
          </mat-form-field>

          <mat-form-field appearance="outline" class="full-width">
            <mat-label>Description</mat-label>
            <textarea matInput formControlName="description" placeholder="Enter description"
                      rows="3" maxlength="2000"></textarea>
          </mat-form-field>

          @if (isEdit()) {
            <mat-form-field appearance="outline" class="full-width">
              <mat-label>Status</mat-label>
              <mat-select formControlName="status">
                @for (s of statusOptions; track s) {
                  <mat-option [value]="s">{{ s }}</mat-option>
                }
              </mat-select>
            </mat-form-field>
          }

          <div formGroupName="parameters" class="parameters-section">
            <h3 class="section-title">Parameters</h3>

            <div class="parameters-grid">
              <mat-form-field appearance="outline">
                <mat-label>Distribution</mat-label>
                <mat-select formControlName="distribution">
                  @for (d of distributionOptions; track d) {
                    <mat-option [value]="d">{{ d }}</mat-option>
                  }
                </mat-select>
                @if (form.controls.parameters.controls.distribution.hasError('required')) {
                  <mat-error>Distribution is required</mat-error>
                }
              </mat-form-field>

              <mat-form-field appearance="outline">
                <mat-label>Mean</mat-label>
                <input matInput type="number" formControlName="mean" step="any">
                @if (form.controls.parameters.controls.mean.hasError('required')) {
                  <mat-error>Mean is required</mat-error>
                }
              </mat-form-field>

              <mat-form-field appearance="outline">
                <mat-label>Std Dev</mat-label>
                <input matInput type="number" formControlName="stdDev" step="any" min="0.0001">
                @if (form.controls.parameters.controls.stdDev.hasError('required')) {
                  <mat-error>Standard deviation is required</mat-error>
                } @else if (form.controls.parameters.controls.stdDev.hasError('min')) {
                  <mat-error>Must be greater than 0</mat-error>
                }
              </mat-form-field>

              <mat-form-field appearance="outline">
                <mat-label>Sample Size</mat-label>
                <input matInput type="number" formControlName="sampleSize" min="1" max="100000">
                @if (form.controls.parameters.controls.sampleSize.hasError('required')) {
                  <mat-error>Sample size is required</mat-error>
                } @else if (form.controls.parameters.controls.sampleSize.hasError('min')) {
                  <mat-error>Must be at least 1</mat-error>
                } @else if (form.controls.parameters.controls.sampleSize.hasError('max')) {
                  <mat-error>Must be at most 100,000</mat-error>
                }
              </mat-form-field>
            </div>
          </div>

          <div class="form-actions">
            <button mat-button type="button" (click)="onCancel()" [disabled]="saving()">Cancel</button>
            <button mat-stroked-button type="button" (click)="onClear()" [disabled]="saving()">
              <mat-icon>clear</mat-icon>
              Clear
            </button>
            <button mat-flat-button color="primary" type="submit"
                    [disabled]="!canSubmit()">
              @if (saving()) {
                <mat-spinner diameter="20"></mat-spinner>
              } @else {
                {{ isEdit() ? 'Update' : 'Create' }}
              }
            </button>
          </div>
        </form>
      </mat-card-content>
    </mat-card>
  }
</div>

// ui/components/model-form.tsx
'use client';

import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { useRouter } from 'next/navigation';
import { ErrorNotice, Loading } from './loading';
import { errorMessage } from '@/lib/format';
import { useApi } from '@/lib/use-api';
import type { ModelStatus } from '@/lib/types';

interface FormState {
  readonly name: string;
  readonly description: string;
  readonly status: ModelStatus;
  readonly distribution: string;
  readonly mean: string;
  readonly stdDev: string;
  readonly sampleSize: string;
}

const emptyForm: FormState = {
  name: '',
  description: '',
  status: 'Draft',
  distribution: '',
  mean: '',
  stdDev: '',
  sampleSize: '',
};

export function ModelForm({ modelId }: { readonly modelId?: string }) {
  const api = useApi();
  const router = useRouter();
  const [form, setForm] = useState<FormState>(emptyForm);
  const [baseline, setBaseline] = useState<FormState>(emptyForm);
  const [loading, setLoading] = useState(Boolean(modelId));
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');
  const draftKey = `ea:model-form:${modelId ?? 'new'}`;

  useEffect(() => {
    if (!api) return;
    if (!modelId) {
      const draft = localStorage.getItem(draftKey);
      if (draft) setForm(JSON.parse(draft) as FormState);
      return;
    }
    void api.getModel(modelId)
      .then(model => {
        const value: FormState = {
          name: model.name,
          description: model.description ?? '',
          status: model.status,
          distribution: String(model.parameters?.distribution ?? 'normal'),
          mean: String(model.parameters?.mean ?? 0),
          stdDev: String(model.parameters?.stdDev ?? 1),
          sampleSize: String(model.parameters?.sampleSize ?? 1000),
        };
        setBaseline(value);
        const draft = localStorage.getItem(draftKey);
        setForm(draft ? JSON.parse(draft) as FormState : value);
      })
      .catch(reason => setError(errorMessage(reason)))
      .finally(() => setLoading(false));
  }, [api, modelId, draftKey]);

  useEffect(() => {
    const timer = window.setTimeout(() => localStorage.setItem(draftKey, JSON.stringify(form)), 300);
    return () => window.clearTimeout(timer);
  }, [draftKey, form]);

  const valid = useMemo(() => form.name.trim().length > 0
    && form.name.length <= 200
    && form.description.length <= 2000
    && form.distribution.length > 0
    && Number.isFinite(Number(form.mean))
    && Number(form.stdDev) >= 0.0001
    && Number(form.sampleSize) >= 1
    && Number(form.sampleSize) <= 100000
    && JSON.stringify(form) !== JSON.stringify(baseline), [form, baseline]);

  const update = (field: keyof FormState, value: string) => setForm(current => ({ ...current, [field]: value }));

  const submit = async (event: FormEvent) => {
    event.preventDefault();
    if (!api || !valid) return;
    setSaving(true);
    setError('');
    const input = {
      name: form.name.trim(),
      description: form.description.trim() || null,
      status: form.status,
      parameters: {
        distribution: form.distribution,
        mean: Number(form.mean),
        stdDev: Number(form.stdDev),
        sampleSize: Number(form.sampleSize),
      },
    };
    try {
      const model = modelId ? await api.updateModel(modelId, input) : await api.createModel(input);
      localStorage.removeItem(draftKey);
      router.push(`/models/${model.id}`);
    } catch (reason) {
      setError(errorMessage(reason));
      setSaving(false);
    }
  };

  if (loading) return <Loading label="Loading model" />;

  return (
    <div className="page">
      <div className="page-header"><h1>{modelId ? 'Edit Model' : 'New Model'}</h1></div>
      {error && <ErrorNotice message={error} />}
      <section className="card"><div className="card-body">
        <form className="form-grid" onSubmit={event => void submit(event)}>
          <div className="field"><label htmlFor="name">Name</label><input id="name" className="input" maxLength={200} required value={form.name} onChange={event => update('name', event.target.value)} /></div>
          <div className="field"><label htmlFor="description">Description</label><textarea id="description" className="textarea" maxLength={2000} value={form.description} onChange={event => update('description', event.target.value)} /></div>
          {modelId && <div className="field"><label htmlFor="status">Status</label><select id="status" className="select" value={form.status} onChange={event => update('status', event.target.value)}><option>Draft</option><option>Active</option><option>Archived</option></select></div>}
          <div><h2>Parameters</h2><div className="parameter-grid">
            <div className="field"><label htmlFor="distribution">Distribution</label><select id="distribution" className="select" required value={form.distribution} onChange={event => update('distribution', event.target.value)}><option value="">Select</option><option value="normal">normal</option><option value="uniform">uniform</option><option value="exponential">exponential</option><option value="lognormal">lognormal</option></select></div>
            <div className="field"><label htmlFor="mean">Mean</label><input id="mean" className="input" type="number" step="any" required value={form.mean} onChange={event => update('mean', event.target.value)} /></div>
            <div className="field"><label htmlFor="stdDev">Std Dev</label><input id="stdDev" className="input" type="number" step="any" min="0.0001" required value={form.stdDev} onChange={event => update('stdDev', event.target.value)} /></div>
            <div className="field"><label htmlFor="sampleSize">Sample Size</label><input id="sampleSize" className="input" type="number" min="1" max="100000" required value={form.sampleSize} onChange={event => update('sampleSize', event.target.value)} /></div>
          </div></div>
          <div className="form-actions">
            <button className="button ghost" type="button" onClick={() => { localStorage.removeItem(draftKey); router.push(modelId ? `/models/${modelId}` : '/models'); }}>Cancel</button>
            <button className="button secondary" type="button" onClick={() => setForm(emptyForm)}>Clear</button>
            <button className="button primary" type="submit" disabled={!valid || saving}>{saving ? 'Saving…' : modelId ? 'Update' : 'Create'}</button>
          </div>
        </form>
      </div></section>
    </div>
  );
}
