// ui/components/Histogram.tsx
import type { HistogramData } from '@/lib/types';

/** Renders precomputed histogram data as an accessible responsive SVG. */
export function Histogram({ data }: { readonly data: HistogramData }) {
  const width = 640;
  const height = 280;
  const margin = { top: 16, right: 16, bottom: 36, left: 46 };
  const chartWidth = width - margin.left - margin.right;
  const chartHeight = height - margin.top - margin.bottom;
  const max = Math.max(...data.counts, 1);
  const barWidth = chartWidth / Math.max(data.counts.length, 1);

  return (
    <svg className="w-full max-w-[760px]" viewBox={`0 0 ${width} ${height}`} role="img" aria-label={`Histogram with ${data.counts.length} bins`}>
      <line className="stroke-border stroke-1" x1={margin.left} y1={margin.top} x2={margin.left} y2={margin.top + chartHeight} />
      <line className="stroke-border stroke-1" x1={margin.left} y1={margin.top + chartHeight} x2={margin.left + chartWidth} y2={margin.top + chartHeight} />
      {data.counts.map((count, index) => {
        const barHeight = count / max * chartHeight;
        return (
          <rect
            className="fill-primary opacity-85"
            key={`${data.binEdges[index]}-${index}`}
            x={margin.left + index * barWidth}
            y={margin.top + chartHeight - barHeight}
            width={Math.max(barWidth - 1, 1)}
            height={barHeight}
          >
            <title>{data.binEdges[index]?.toFixed(2)} – {data.binEdges[index + 1]?.toFixed(2)}: {count}</title>
          </rect>
        );
      })}
      <text className="fill-muted text-xs" x={width / 2} y={height - 4} textAnchor="middle">Value</text>
      <text className="fill-muted text-xs" x={14} y={height / 2} textAnchor="middle" transform={`rotate(-90 14 ${height / 2})`}>Count</text>
    </svg>
  );
}

// ui/src/app/shared/components/histogram/histogram.component.ts
import { Component, computed, input } from '@angular/core';
import { DecimalPipe } from '@angular/common';
import { HistogramData } from '../../models/model-run.interface';

/**
 * Pure presentation component that renders a pre-computed histogram
 * as responsive inline SVG with axes, labels, and hover tooltips.
 */
@Component({
  selector: 'app-histogram',
  standalone: true,
  imports: [DecimalPipe],
  template: `
    <svg [attr.viewBox]="viewBox" class="histogram-svg" preserveAspectRatio="xMidYMid meet"
         role="img" [attr.aria-label]="'Histogram with ' + data().counts.length + ' bins'">
      <!-- Y axis line -->
      <line [attr.x1]="margin.left" [attr.y1]="margin.top"
            [attr.x2]="margin.left" [attr.y2]="margin.top + chartHeight"
            stroke="rgba(0,0,0,0.2)" stroke-width="1" />

      <!-- X axis line -->
      <line [attr.x1]="margin.left" [attr.y1]="margin.top + chartHeight"
            [attr.x2]="margin.left + chartWidth" [attr.y2]="margin.top + chartHeight"
            stroke="rgba(0,0,0,0.2)" stroke-width="1" />

      <!-- Y axis ticks and grid lines -->
      @for (tick of yTicks(); track tick.value) {
        <text [attr.x]="margin.left - 8" [attr.y]="tick.y + 4"
              text-anchor="end" class="axis-label">{{ tick.value }}</text>
        <line [attr.x1]="margin.left" [attr.y1]="tick.y"
              [attr.x2]="margin.left + chartWidth" [attr.y2]="tick.y"
              stroke="rgba(0,0,0,0.05)" stroke-width="1" />
      }

      <!-- X axis ticks -->
      @for (tick of xTicks(); track tick.x) {
        <text [attr.x]="tick.x" [attr.y]="margin.top + chartHeight + 20"
              text-anchor="middle" class="axis-label">{{ tick.value | number:'1.1-1' }}</text>
      }

      <!-- Bars -->
      @for (bar of bars(); track bar.x) {
        <rect [attr.x]="bar.x" [attr.y]="bar.y"
              [attr.width]="bar.width" [attr.height]="bar.height"
              class="bar">
          <title>{{ bar.binStart | number:'1.2-2' }} – {{ bar.binEnd | number:'1.2-2' }}: {{ bar.count }}</title>
        </rect>
      }

      <!-- Axis labels -->
      <text [attr.x]="margin.left + chartWidth / 2" [attr.y]="height - 2"
            text-anchor="middle" class="axis-title">Value</text>
      <text [attr.x]="12" [attr.y]="margin.top + chartHeight / 2"
            text-anchor="middle" class="axis-title"
            [attr.transform]="'rotate(-90, 12, ' + (margin.top + chartHeight / 2) + ')'">Count</text>
    </svg>
  `,
  styles: [`
    :host {
      display: block;
    }

    .histogram-svg {
      width: 100%;
      max-width: 700px;
      height: auto;
    }

    .bar {
      fill: #1976d2;
      opacity: 0.85;

      &:hover {
        opacity: 1;
        fill: #1565c0;
      }
    }

    .axis-label {
      font-size: 11px;
      fill: rgba(0, 0, 0, 0.54);
    }

    .axis-title {
      font-size: 12px;
      fill: rgba(0, 0, 0, 0.6);
      font-weight: 500;
    }
  `],
})
export class HistogramComponent {
  /** Pre-computed histogram data to render. */
  readonly data = input.required<HistogramData>();

  /** SVG canvas dimensions. */
  private readonly width = 600;
  readonly height = 300;
  readonly margin = { top: 20, right: 20, bottom: 40, left: 50 } as const;

  readonly chartWidth = this.width - this.margin.left - this.margin.right;
  readonly chartHeight = this.height - this.margin.top - this.margin.bottom;
  readonly viewBox = `0 0 ${this.width} ${this.height}`;

  /** Computed bar rectangles mapped from histogram counts. */
  readonly bars = computed(() => {
    const d = this.data();
    if (!d || d.counts.length === 0) return [];

    const maxCount = Math.max(...d.counts);
    const barWidth = this.chartWidth / d.counts.length;

    return d.counts.map((count, i) => ({
      x: this.margin.left + i * barWidth,
      y: this.margin.top + this.chartHeight - (maxCount > 0 ? (count / maxCount) * this.chartHeight : 0),
      width: Math.max(barWidth - 1, 1),
      height: maxCount > 0 ? (count / maxCount) * this.chartHeight : 0,
      count,
      binStart: d.binEdges[i],
      binEnd: d.binEdges[i + 1],
    }));
  });

  /** Y-axis ticks (5 evenly spaced from 0 to max count). */
  readonly yTicks = computed(() => {
    const d = this.data();
    if (!d || d.counts.length === 0) return [];
    const maxCount = Math.max(...d.counts);
    return [0, 0.25, 0.5, 0.75, 1].map(pct => ({
      value: Math.round(maxCount * pct),
      y: this.margin.top + this.chartHeight - pct * this.chartHeight,
    }));
  });

  /** X-axis ticks (up to 5 evenly spaced bin edge labels). */
  readonly xTicks = computed(() => {
    const d = this.data();
    if (!d || d.binEdges.length === 0) return [];
    const edges = d.binEdges;
    const step = Math.max(1, Math.floor(edges.length / 5));
    const ticks: Array<{ value: number; x: number }> = [];
    for (let i = 0; i < edges.length; i += step) {
      ticks.push({
        value: edges[i],
        x: this.margin.left + (i / (edges.length - 1)) * this.chartWidth,
      });
    }
    return ticks;
  });
}
