// ui/src/app/features/dashboard/dashboard.component.ts
import { Component, inject, OnInit, signal } from '@angular/core';
import { Router, RouterLink } from '@angular/router';
import { MatCardModule } from '@angular/material/card';
import { MatTableModule } from '@angular/material/table';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { DatePipe } from '@angular/common';
import { ModelService } from '../../core/services/model.service';
import { StatusBadgeComponent } from '../../shared/components/status-badge/status-badge.component';
import { Model } from '../../shared/models/model.interface';

@Component({
  selector: 'app-dashboard',
  standalone: true,
  imports: [
    MatCardModule,
    MatTableModule,
    MatButtonModule,
    MatIconModule,
    MatProgressSpinnerModule,
    DatePipe,
    StatusBadgeComponent,
    RouterLink,
  ],
  templateUrl: './dashboard.component.html',
  styleUrl: './dashboard.component.scss',
})
export class DashboardComponent implements OnInit {
  private readonly modelService = inject(ModelService);
  private readonly router = inject(Router);

  readonly loading = signal(true);
  readonly totalModels = signal(0);
  readonly activeModels = signal(0);
  readonly recentModels = signal<Model[]>([]);
  readonly displayedColumns = ['name', 'status', 'version', 'updatedAtUtc'];

  ngOnInit(): void {
    this.loadDashboard();
  }

  private loadDashboard(): void {
    this.loading.set(true);

    this.modelService.getModels(1, 5).subscribe({
      next: result => {
        this.recentModels.set(result.items);
        this.totalModels.set(result.totalCount);
      },
      error: () => this.loading.set(false),
    });

    this.modelService.getModels(1, 1, 'Active').subscribe({
      next: result => {
        this.activeModels.set(result.totalCount);
        this.loading.set(false);
      },
      error: () => this.loading.set(false),
    });
  }

  navigateToModel(model: Model): void {
    this.router.navigate(['/models', model.id]);
  }

  navigateToModels(): void {
    this.router.navigate(['/models']);
  }
}

<div class="page-container">
  <div class="page-header">
    <h1 class="page-title">Dashboard</h1>
  </div>

  @if (loading()) {
    <div class="loading-container">
      <mat-spinner diameter="40"></mat-spinner>
    </div>
  } @else {
    <div class="card-grid">
      <mat-card>
        <mat-card-header>
          <mat-icon mat-card-avatar>science</mat-icon>
          <mat-card-title>{{ totalModels() }}</mat-card-title>
          <mat-card-subtitle>Total Models</mat-card-subtitle>
        </mat-card-header>
      </mat-card>

      <mat-card>
        <mat-card-header>
          <mat-icon mat-card-avatar>check_circle</mat-icon>
          <mat-card-title>{{ activeModels() }}</mat-card-title>
          <mat-card-subtitle>Active Models</mat-card-subtitle>
        </mat-card-header>
      </mat-card>
    </div>

    <mat-card>
      <mat-card-header>
        <mat-card-title>Recent Models</mat-card-title>
        <span class="spacer"></span>
        <button mat-button color="primary" (click)="navigateToModels()">View All</button>
      </mat-card-header>
      <mat-card-content>
        @if (recentModels().length === 0) {
          <div class="empty-state">
            <mat-icon>inbox</mat-icon>
            <p>No models yet. Create your first model to get started.</p>
            <button mat-flat-button color="primary" routerLink="/models/new">Create Model</button>
          </div>
        } @else {
          <table mat-table [dataSource]="recentModels()" class="full-width">
            <ng-container matColumnDef="name">
              <th mat-header-cell *matHeaderCellDef>Name</th>
              <td mat-cell *matCellDef="let model">{{ model.name }}</td>
            </ng-container>

            <ng-container matColumnDef="status">
              <th mat-header-cell *matHeaderCellDef>Status</th>
              <td mat-cell *matCellDef="let model">
                <app-status-badge [status]="model.status" />
              </td>
            </ng-container>

            <ng-container matColumnDef="version">
              <th mat-header-cell *matHeaderCellDef>Version</th>
              <td mat-cell *matCellDef="let model">v{{ model.version }}</td>
            </ng-container>

            <ng-container matColumnDef="updatedAtUtc">
              <th mat-header-cell *matHeaderCellDef>Updated</th>
              <td mat-cell *matCellDef="let model">{{ model.updatedAtUtc | date:'short' }}</td>
            </ng-container>

            <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
            <tr mat-row *matRowDef="let model; columns: displayedColumns"
                class="clickable-row" (click)="navigateToModel(model)"></tr>
          </table>
        }
      </mat-card-content>
    </mat-card>
  }
</div>

// ui/app/(authenticated)/dashboard/page.tsx
'use client';

import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useEffect, useState } from 'react';
import { Activity, TestTube2 } from 'lucide-react';
import { ErrorNotice, Loading } from '@/components/loading';
import { StatusBadge } from '@/components/status-badge';
import { useApi } from '@/lib/use-api';
import { errorMessage, formatDate } from '@/lib/format';
import type { Model } from '@/lib/types';

export default function DashboardPage() {
  const api = useApi();
  const router = useRouter();
  const [models, setModels] = useState<Model[]>([]);
  const [total, setTotal] = useState(0);
  const [active, setActive] = useState(0);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  useEffect(() => {
    if (!api) return;
    setLoading(true);
    void Promise.all([api.getModels(1, 5), api.getModels(1, 1, 'Active')])
      .then(([recent, activeModels]) => {
        setModels(recent.items);
        setTotal(recent.totalCount);
        setActive(activeModels.totalCount);
      })
      .catch(reason => setError(errorMessage(reason)))
      .finally(() => setLoading(false));
  }, [api]);

  return (
    <div className="page">
      <div className="page-header"><h1>Dashboard</h1></div>
      {error && <ErrorNotice message={error} />}
      {loading ? <Loading label="Loading dashboard" /> : (
        <>
          <div className="stat-grid">
            <div className="card stat-card"><span className="stat-icon"><TestTube2 /></span><div><span className="stat-value">{total}</span><span className="stat-label">Total Models</span></div></div>
            <div className="card stat-card"><span className="stat-icon"><Activity /></span><div><span className="stat-value">{active}</span><span className="stat-label">Active Models</span></div></div>
          </div>
          <section className="card">
            <div className="card-header"><h2>Recent Models</h2><span className="spacer" /><Link className="button ghost" href="/models">View All</Link></div>
            {models.length === 0 ? (
              <div className="empty-state"><p>No models yet.</p><Link className="button primary" href="/models/new">Create Model</Link></div>
            ) : (
              <div className="table-wrap"><table><thead><tr><th>Name</th><th>Status</th><th>Version</th><th>Updated</th></tr></thead><tbody>
                {models.map(model => <tr className="clickable-row" key={model.id} onClick={() => router.push(`/models/${model.id}`)}><td>{model.name}</td><td><StatusBadge status={model.status} /></td><td>v{model.version}</td><td>{formatDate(model.updatedAtUtc, 'short')}</td></tr>)}
              </tbody></table></div>
            )}
          </section>
        </>
      )}
    </div>
  );
}
